package com.spotifyradar.app

import java.text.Normalizer

object KworbData {
    val TOP_500 = listOf(
        "Bruno Mars",
        "Justin Bieber",
        "Rihanna",
        "The Weeknd",
        "Taylor Swift",
        "Shakira",
        "Lady Gaga",
        "Ariana Grande",
        "Bad Bunny",
        "Drake",
        "Coldplay",
        "Michael Jackson",
        "Katy Perry",
        "David Guetta",
        "Pitbull",
        "Maroon 5",
        "Ed Sheeran",
        "Calvin Harris",
        "Billie Eilish",
        "Eminem",
        "J Balvin",
        "Post Malone",
        "Dua Lipa",
        "Kanye West",
        "Sia",
        "Kendrick Lamar",
        "Black Eyed Peas",
        "Olivia Rodrigo",
        "BeyoncГ©",
        "SZA",
        "Daddy Yankee",
        "Lana Del Rey",
        "Harry Styles",
        "KAROL G",
        "Tame Impala",
        "Sean Paul",
        "Travis Scott",
        "Justin Timberlake",
        "Adele",
        "Shawn Mendes",
        "Miley Cyrus",
        "Zara Larsson",
        "Chris Brown",
        "Linkin Park",
        "Sam Smith",
        "Marshmello",
        "Sabrina Carpenter",
        "Arctic Monkeys",
        "Doja Cat",
        "Halsey",
        "Shreya Ghoshal",
        "Ellie Goulding",
        "Madonna",
        "Arijit Singh",
        "sombr",
        "Ozuna",
        "Elton John",
        "Rauw Alejandro",
        "Khalid",
        "Imagine Dragons",
        "The Chainsmokers",
        "Alicia Keys",
        "Burna Boy",
        "Swae Lee",
        "Future",
        "Dominic Fike",
        "Fleetwood Mac",
        "Olivia Dean",
        "Pritam",
        "Britney Spears",
        "Ne-Yo",
        "JAY-Z",
        "Camila Cabello",
        "JENNIE",
        "Maluma",
        "OneRepublic",
        "Queen",
        "Charlie Puth",
        "USHER",
        "Red Hot Chili Peppers",
        "DJ Snake",
        "Lil Wayne",
        "Fuerza Regida",
        "The Neighbourhood",
        "A.R. Rahman",
        "Alex Warren",
        "Farruko",
        "Nicki Minaj",
        "Kesha",
        "Jennifer Lopez",
        "Anuel AA",
        "Radiohead",
        "Flo Rida",
        "Selena Gomez",
        "One Direction",
        "50 Cent",
        "Peso Pluma",
        "Bebe Rexha",
        "Green Day",
        "Wiz Khalifa",
        "Diplo",
        "Oasis",
        "Myke Towers",
        "RAYE",
        "ABBA",
        "The Kid LAROI",
        "Mac Miller",
        "Don Toliver",
        "Tate McRae",
        "HUGEL",
        "Don Omar",
        "Daniel Caesar",
        "Metro Boomin",
        "Akon",
        "Teddy Swims",
        "The Goo Goo Dolls",
        "Avicii",
        "P!nk",
        "21 Savage",
        "Benson Boone",
        "Playboi Carti",
        "Disney",
        "Guns N' Roses",
        "Pharrell Williams",
        "Twenty One Pilots",
        "The Police",
        "Empire Of The Sun",
        "Malcolm Todd",
        "Hozier",
        "Nirvana",
        "Jason Derulo",
        "Romeo Santos",
        "A\$AP Rocky",
        "Frank Ocean",
        "Anitta",
        "Grupo Frontera",
        "AC/DC",
        "Gorillaz",
        "Nicky Jam",
        "Tyler, The Creator",
        "Demi Lovato",
        "Feid",
        "Manuel Turizo",
        "J. Cole",
        "Irshad Kamil",
        "KATSEYE",
        "Steve Lacy",
        "Mariah Carey",
        "Enrique Iglesias",
        "The Beatles",
        "The Killers",
        "Tems",
        "Bon Jovi",
        "Nelly Furtado",
        "Clean Bandit",
        "Paramore",
        "Sachin-Jigar",
        "Ty Dolla \$ign",
        "Gracie Abrams",
        "Mithoon",
        "Kali Uchis",
        "Djo",
        "Morgan Wallen",
        "TiГ«sto",
        "Amitabh Bhattacharya",
        "Ravyn Lenae",
        "Anne-Marie",
        "Mark Ronson",
        "Becky G",
        "Ovy On The Drums",
        "Snoop Dogg",
        "Christina Aguilera",
        "Udit Narayan",
        "The Cranberries",
        "Childish Gambino",
        "Quevedo",
        "Macklemore",
        "Major Lazer",
        "BTS",
        "The Script",
        "Billy Joel",
        "Creedence Clearwater Revival",
        "Ryan Castro",
        "Vishal-Shekhar",
        "Ella Langley",
        "Gunna",
        "Metallica",
        "Miguel",
        "Sayeed Quadri",
        "Bee Gees",
        "The MarГ­as",
        "Phil Collins",
        "Omar Courtz",
        "Vance Joy",
        "BeГ©le",
        "Noah Kahan",
        "Temper City",
        "Tanishk Bagchi",
        "Backstreet Boys",
        "Cardi B",
        "Atif Aslam",
        "Cris MJ",
        "JHAYCO",
        "Cigarettes After Sex",
        "XXXTENTACION",
        "Dave",
        "Kodak Black",
        "ArcГЎngel",
        "Lil Baby",
        "Bryan Adams",
        "French Montana",
        "Dolly Parton",
        "Chappell Roan",
        "Neton Vega",
        "Sunidhi Chauhan",
        "Whitney Houston",
        "DaBaby",
        "Shankar Mahadevan",
        "KK",
        "Natasha Bedingfield",
        "Gigi Perez",
        "Junior H",
        "Danny Ocean",
        "Lil Uzi Vert",
        "Daft Punk",
        "Outkast",
        "Zion & Lennox",
        "Keyshia Cole",
        "Juice WRLD",
        "PinkPantheress",
        "SIENNA SPIRO",
        "Nickelback",
        "The Rolling Stones",
        "G-Eazy",
        "Timbaland",
        "Tom Odell",
        "Avril Lavigne",
        "Wisin & Yandel",
        "ZAYN",
        "CarГ­n LeГіn",
        "Plan B",
        "Young Thug",
        "Kumaar",
        "Eagles",
        "Alan Walker",
        "James Arthur",
        "Chencho Corleone",
        "Kygo",
        "Journey",
        "AFROJACK",
        "Aerosmith",
        "Swedish House Mafia",
        "2Pac",
        "Jess Glynne",
        "PARTYNEXTDOOR",
        "Charli xcx",
        "Robin Schulz",
        "Tainy",
        "ManГЎ",
        "benny blanco",
        "Sean Kingston",
        "Ava Max",
        "Tinashe",
        "B.o.B",
        "TOTO",
        "Pink Floyd",
        "Г‘engo Flow",
        "Mohit Chauhan",
        "The Notorious B.I.G.",
        "Joji",
        "Sonu Nigam",
        "Yandel",
        "Panic! At The Disco",
        "Daryl Hall & John Oates",
        "Bizarrap",
        "Vishal Mishra",
        "Kehlani",
        "Sade",
        "Alka Yagnik",
        "Kid Cudi",
        "Dire Straits",
        "Evanescence",
        "Kings of Leon",
        "Rema",
        "Lord Huron",
        "Lorde",
        "The Cure",
        "Prince Royce",
        "Tyla",
        "El Alfa",
        "Shaggy",
        "ROSALГЌA",
        "Fall Out Boy",
        "Gwen Stefani",
        "ROSГ‰",
        "KPop Demon Hunters Cast",
        "Aventura",
        "Blessd",
        "Trippie Redd",
        "Bob Marley & The Wailers",
        "Luke Combs",
        "System Of A Down",
        "Shankar-Ehsaan-Loy",
        "Nelly",
        "Natanael Cano",
        "Oscar Maydon",
        "Manoj Muntashir",
        "Megan Thee Stallion",
        "Florence + The Machine",
        "Earth, Wind & Fire",
        "Chinmayi",
        "Tory Lanez",
        "Kelly Clarkson",
        "Luis Fonsi",
        "Tove Lo",
        "Chris Stapleton",
        "El Bogueto",
        "Tito Double P",
        "Alok",
        "T-Pain",
        "Himesh Reshammiya",
        "Tears For Fears",
        "Jack Harlow",
        "Fred again..",
        "Train",
        "beabadoobee",
        "Anirudh Ravichander",
        "Sebastian Yatra",
        "Jay Wheeler",
        "Shashwat Sachdev",
        "DJ Khaled",
        "Doechii",
        "Tyga",
        "Lewis Capaldi",
        "Glass Animals",
        "GIVД’ON",
        "EJAE",
        "Elvis Presley",
        "a-ha",
        "Foo Fighters",
        "Badshah",
        "Martin Garrix",
        "Sameer Anjaan",
        "The Smiths",
        "Macklemore & Ryan Lewis",
        "R.E.M.",
        "Disclosure",
        "Zach Bryan",
        "U2",
        "Marvin Gaye",
        "TV Girl",
        "Lola Young",
        "Bastille",
        "Grupo Firme",
        "Amit Trivedi",
        "MГҐneskin",
        "Brent Faiyaz",
        "The Offspring",
        "Amaal Mallik",
        "Gabito Ballesteros",
        "Keane",
        "Carly Rae Jepsen",
        "Rels B",
        "REI AMI",
        "Weezer",
        "Prince",
        "Lost Frequencies",
        "Dr. Dre",
        "Limp Bizkit",
        "Anuv Jain",
        "Javed Ali",
        "Amy Winehouse",
        "SOLTO (FR)",
        "Led Zeppelin",
        "Rahat Fateh Ali Khan",
        "HUNTR/X",
        "Anderson .Paak",
        "Gym Class Heroes",
        "Bonnie Tyler",
        "AUDREY NUNA",
        "Vishal Dadlani",
        "Jonas Blue",
        "Yung Beef",
        "De La Ghetto",
        "George Michael",
        "De La Soul",
        "Shilpa Rao",
        "Kapo",
        "Lenny TavГЎrez",
        "Sajid-Wajid",
        "Mc Gw",
        "Sech",
        "Anu Malik",
        "Gotye",
        "John Legend",
        "MGMT",
        "Luis Miguel",
        "Big Sean",
        "Bruce Springsteen",
        "Zion",
        "Central Cee",
        "Young Miko",
        "Rex Orange County",
        "Marco Antonio SolГ­s",
        "Ray Dalton",
        "Skrillex",
        "Foreigner",
        "Stevie Wonder",
        "Luis R Conriquez",
        "Mike Posner",
        "Lynyrd Skynyrd",
        "Lily-Rose Depp",
        "Justin Quiles",
        "Bob Sinclar",
        "Aitana",
        "David Bowie",
        "Mac DeMarco",
        "LAUV",
        "Gucci Mane",
        "Jessie J",
        "Tulus",
        "Camilo",
        "Sachet-Parampara",
        "ILLIT",
        "JVKE",
        "Shaarib Toshi",
        "Laufey",
        "Reik",
        "Shaboozey",
        "Muse",
        "5 Seconds of Summer",
        "Conan Gray",
        "Meghan Trainor",
        "Jubin Nautiyal",
        "Kylie Minogue",
        "Alessia Cara",
        "Ayra Starr",
        "Juanes",
        "The 1975",
        "Bryson Tiller",
        "Kimbra",
        "Calle 24",
        "Migos",
        "FloyyMenor",
        "blink-182",
        "Three Days Grace",
        "Mitski",
        "Fetty Wap",
        "The Fray",
        "Zedd",
        "Billy Idol",
        "Harris Jayaraj",
        "Sachet Tandon",
        "Chino Pacas",
        "Mora",
        "LE SSERAFIM",
        "Neeti Mohan",
        "BigXthaPlug",
        "Jeet Gannguli",
        "rusowsky",
        "De La Rose",
        "Mustafa Zahid",
        "Jason Mraz",
        "Bill Withers",
        "Depeche Mode",
        "Scorpions",
        "Clairo",
        "Ricky Martin",
        "Jowell & Randy",
        "Wisin",
        "Lil Nas X",
        "Marc Anthony",
        "JuliГіn ГЃlvarez y su NorteГ±o Banda",
        "Rae Sremmurd",
        "Topic",
        "Raim Laode",
        "Troye Sivan",
        "Banda MS de Sergio LizГЎrraga",
        "Dei V",
        "MC Meno K",
        "Julieta Venegas",
        "Christian Nodal",
        "Daya",
        "Lenny Kravitz",
        "Foster The People",
        "MC Ryan SP",
        "BLACKPINK",
        "felix jaehn",
        "Noriel",
        "Cyndi Lauper",
        "Disturbed",
        "Alejandro Sanz",
        "Annie Lennox",
        "Lil Peep",
        "Imogen Heap",
        "Chase Atlantic",
        "Jasmine Sandlas",
        "Faheem Abdullah",
        "The Outfield",
        "Lil Durk"
    )

    // Fast lookup map: cleaned name -> Pair(originalName, rank)
    val ARTIST_MAP: Map<String, Pair<String, Int>> by lazy {
        val map = mutableMapOf<String, Pair<String, Int>>()
        TOP_500.forEachIndexed { index, name ->
            val cleaned = clean(name)
            if (cleaned.isNotEmpty() && !map.containsKey(cleaned)) {
                map[cleaned] = Pair(name, index + 1)
            }
        }
        map
    }

    fun clean(str: String): String {
        val normalized = Normalizer.normalize(str.lowercase(), Normalizer.Form.NFD)
        return normalized.replace(Regex("""\p{M}"""), "")
            .replace(Regex("""[^a-z0-9а-яё]"""), "").trim()
    }
}

